framework:
    workflows:
        ticket:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Ticket
            initial_marking: registered
            places:
                - registered
                - paid
                - canceled
            transitions:
                pay:
                    from: registered
                    to: paid
                cancel:
                    from: registered
                    to: canceled
