version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony
    environment:
      - APP_ENV=dev
    depends_on:
      - db
      - rabbitmq

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 15672:15672
      - '5672:5672'
